<a href="https://colab.research.google.com/github/natnut928/GB_Python_libraries/blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание_1

In [1]:
import numpy as np

In [3]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
mean_a=a.mean(axis=0)
mean_a

array([2. , 8.4])

#Задание_2

In [7]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [11]:
a_centered=np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#Задание_3

In [12]:
a1=a_centered[:,0]
a1

array([-1.,  0.,  1.,  1., -1.])

In [13]:
a2=a_centered[:,1]
a2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [14]:
a_centered_sp=np.dot(a1,a2)
a_centered_sp

8.0

In [16]:
N=a.shape[0]
N

5

In [18]:
b=a_centered_sp/(N-1)
b

2.0